default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: book_to_read_development

test:
  <<: *default
  database: book_to_read_test

production:
  <<: *default
  database: book_to_read_production
  username: your_production_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
